saving_dir: 'results/nanogpt'
experiment_name: 'shakesimp_smile_char'
data:
  path: 'data/shakespeare_simple.txt'
  source: 'local'
  data_type: 'text'
  task: 'class_multilabel'
  target_column: null
  target_len: 1
  features:
    - text
  datapoint_limit: null
  flatten: false
  normalize: false
  train_split: 0.9
  valid_split: 0.05
  test_split: 0.05
  augment: identity
model:
  model: GPT
  vocab_size: 65
  context_len: 256
  emb_size: 384
  n_blocks: 6
  n_heads: 6
  bias: false
  dropout: 0.0
  dtype: float32
training:
  warmstart:
    include: true
    optimizer_config:
      # name: 'sgd'
      # parameters:
      #   learning_rate: 0.001
      #   # weight_decay: 0.1
      #   # b1: 0.99
      # lr_schedule: linear
      # lr_schedule_parameters:
      #   init_value: 0.02
      #   end_value: 0.0004
      #   transition_steps: 25200
      name: 'adamw'
      parameters:
        learning_rate: 0.0003
        weight_decay: 0.05
        b1: 0.9
        b2: 0.95
      lr_schedule: linear
      lr_schedule_parameters:
        init_value: 0.0003
        end_value: 0.00025
        transition_steps: 1890
    warmstart_exp_dir: null
    max_epochs: 30
    batch_size: 64
    patience: 30
    permutation_warmstart: false
  sampler:
    name: 'smilet'
    epoch_wise_sampling: false
    batch_size: 128
    warmup_steps: 200
    n_chains: 4
    n_samples: 1000
    use_warmup_as_init: true
    n_thinning: 100
    step_size: 0.0003
    smile_tuning:
      reset_prob: 0.98
      adaption_prob: 0.1
      adaption_strength: 0.02
      smoothing_factor: 0.01
    keep_warmup: false
    prior_config:
      name: StandardNormal
    scheduler_config_warm:
      name: null
      exploration: 0.25
      init_step_size: 0.001
      target_step_size: 0.0
      n_cycles: 4
    scheduler_config_samp:
      name: null
      exploration: 0.25
      init_step_size: 0.001
      target_step_size: 0.0
      n_cycles: 4
  tokenizer:
    tokenizer: 'SingleChar'
    # parameters:
    #   max_vocab_size: 100
    #   pad_len: 64
rng: 1
logging: true
logging_level: INFO
evaluations:
 - PredPerfGPT
evaluation_args:
  phases: [ensemble_initialization, sampling]
  samples_batch_size: 10
  kappa: 0.0
  nominal_coverages:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0
